### ISSUE TITLE
Create Onboarding UI.

### ISSUE THREAD

**Issue by elysian12** [GDSCParulUniversity/Habit-Tracker-App#1]
<img width="658" alt="Screenshot 2022-10-08 at 9 27 03 PM" src="https://user-images.githubusercontent.com/71834118/194716415-74e609bb-b867-4d8b-91b2-a34dba521f89.png">

**Comment by pratikagr** [comment]
Hey, I want to work on this issue.

**Comment by elysian12** [comment]
@pratikagr  please go ahead.
Keep in mind to follow the folder structure/architecture.

**Comment by elysian12** [comment]
@pratikagr any progress ?

**Comment by elysian12** [comment]
![Vector (1)](https://user-images.githubusercontent.com/71834118/194753733-e5df4c69-6021-48b9-b75e-1bcadab78e09.svg)

**Comment by pratikagr** [comment]
> @pratikagr any progress ?

can u provide me the figma link? 
i need those illustarions.
