### ISSUE TITLE
Develop the "Create new Task Screen"

### ISSUE THREAD

**Issue by elysian12** [GDSCParulUniversity/Habit-Tracker-App#13]
When a pr is merged the action should trigger and do these tasks

- [ ] Develop the screen
- [ ] attach the screenshot in the PR

Reference Design
<img width="666" alt="Screenshot 2022-10-09 at 12 31 50 PM" src="https://user-images.githubusercontent.com/71834118/194742837-c7479b9d-434b-404c-b56b-68d6dba0295a.png">

**Comment by gdscpu12** [comment]
@devbathani  please mention the issue whenever you  create a PR.
Ex - "fixes   # 'followed by the issue number' "
