### ISSUE TITLE
Create Login UI.

### ISSUE THREAD

**Issue by elysian12** [GDSCParulUniversity/Habit-Tracker-App#2]
<img width="795" alt="Screenshot 2022-10-08 at 10 13 09 PM" src="https://user-images.githubusercontent.com/71834118/194718189-b03bb9fd-33ca-4053-9312-3689ed0a2d81.png">

**Comment by areeba-farooq** [comment]
Can I work on this??

**Comment by elysian12** [comment]
Sure @SmartAree  please go ahead.

**Comment by areeba-farooq** [comment]
Thanks please assign me.

**Comment by elysian12** [comment]
@SmartAree please resolve the merge conflict so we can close this issue

**Comment by areeba-farooq** [comment]
yeah .. just a little wait.

**Comment by elysian12** [comment]
Nice Work @SmartAree
